import type { Account } from "@offers/config/account";
import { CodeSourceKind } from "@offers/config/code-source-kind";
import type { Credentials } from "@offers/credentials/credentials";
import {
  imapCredentialsFor,
  totpSecretFor,
} from "@offers/credentials/credentials";
import type { NtfyClient } from "@offers/ntfy/ntfy-client";
import { chainCodeSources } from "@offers/one-time-code/chain-code-sources";
import type { CodeSource } from "@offers/one-time-code/code-source";
import { ntfyCodeSource } from "@offers/one-time-code/ntfy-code-source";
import { promptCodeSource } from "@offers/one-time-code/prompt-code-source";
import { totpCodeSource } from "@offers/one-time-code/totp-code-source";
import { imapCodeSource } from "@offers/one-time-code-imap/imap-code-source";
import type {
  ImapCredentials,
  Mailbox,
} from "@offers/one-time-code-imap/imap-mailbox";
import { imapMailbox } from "@offers/one-time-code-imap/imap-mailbox";
import type { TotpParameters } from "@offers/totp/generate-totp";
import { generateTotp } from "@offers/totp/generate-totp";
import { parseOtpauth } from "@offers/totp/parse-otpauth";

export type NtfyTopics = {
  readonly client: NtfyClient;
  readonly alertTopic: string;
  readonly replyTopic: string;
};

export type BuildCodeSourceDeps = {
  readonly credentials: Credentials;
  readonly ntfy: NtfyTopics | undefined;
  readonly makeMailbox?: (credentials: ImapCredentials) => Mailbox;
};

/**
 * Assemble one account's code ladder from its configuration.
 *
 * The order is the account's, not ours — a Chase card enrolled in an
 * authenticator app wants `totp` first and may never need anything else, while
 * an Amex card goes straight to the mailbox. A kind the run cannot actually
 * build (ntfy with no topics, totp with no secret) is a configuration error and
 * fails here, before a browser is ever launched, rather than silently
 * shortening the ladder.
 */
export const buildCodeSource = (
  account: Account,
  deps: BuildCodeSourceDeps,
): CodeSource =>
  chainCodeSources(
    account.codeSources.map((kind) => sourceFor(kind, account, deps)),
  );

const sourceFor = (
  kind: CodeSourceKind,
  account: Account,
  { credentials, ntfy, makeMailbox = imapMailbox }: BuildCodeSourceDeps,
): CodeSource => {
  switch (kind) {
    case CodeSourceKind.Totp: {
      // Resolved now so a missing or malformed secret fails before a browser
      // launches; only the code itself, which depends on the clock, is lazy.
      const parameters = totpParametersFor(account, credentials);
      return totpCodeSource(() =>
        Promise.resolve(generateTotp(parameters, new Date())),
      );
    }
    case CodeSourceKind.Imap:
      return imapCodeSource({
        mailbox: makeMailbox(mailbox(account, credentials)),
      });
    case CodeSourceKind.Ntfy:
      return ntfyCodeSource({ ...requireNtfy(account, ntfy) });
    case CodeSourceKind.Prompt:
      return promptCodeSource();
  }
};

/**
 * Generated by us rather than fetched from a password manager: the secret sits
 * in the credentials document alongside the password it protects, so the only
 * thing this service can reach is the four bank logins.
 */
const totpParametersFor = (
  account: Account,
  credentials: Credentials,
): TotpParameters => {
  const totpSecret = totpSecretFor(credentials, account.id);
  if (totpSecret === undefined) {
    throw new Error(
      `account "${account.id}" asks for totp codes but has no totpSecret`,
    );
  } else {
    return parseOtpauth(totpSecret);
  }
};

const mailbox = (
  account: Account,
  credentials: Credentials,
): ImapCredentials => {
  const imap = account.imap;
  if (imap === undefined) {
    throw new Error(
      `account "${account.id}" asks for imap codes but no imap block is configured`,
    );
  } else {
    const { user, password } = imapCredentialsFor(credentials, account.id);
    return {
      folder: imap.folder,
      host: imap.host,
      password,
      port: imap.port,
      secure: imap.secure,
      user,
    };
  }
};

const requireNtfy = (
  account: Account,
  ntfy: NtfyTopics | undefined,
): NtfyTopics => {
  if (ntfy === undefined) {
    throw new Error(
      `account "${account.id}" asks for ntfy codes but no ntfy block is configured`,
    );
  } else {
    return ntfy;
  }
};
